sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk7

env: 
  - DOCKER_VERSION=1.10.3
  - DOCKER_VERSION=1.11.1

before_install:
  # check what version of docker is installed beforehand
  - dpkg -l | grep docker
  # install the version of docker in the DOCKER_VERSION env var
  - ./.travis.sh install_docker
  # double-check that the version/config is correct
  - ./.travis.sh dump_docker_config
  - docker version
  - docker info

script: mvn test

after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)

# dump the docker logs in case they are needed for troubleshooting failures
after_script:
  - sudo cat /var/log/upstart/docker.log
